name: food_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  intl: ^0.20.2 # Kiểm tra phiên bản mới nhất trên pub.dev
  shared_preferences: ^2.0.0 # Hoặc phiên bản mới nhất
  url_launcher: ^6.2.5 # Thêm dòng này để mở link thanh toán (VNPay, Momo)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

